### ISSUE TITLE
svg not shown in dokuwiki when plugin is activated

### ISSUE THREAD

**Issue by FiC5020** [restlessminded/dokuwiki-plugin-svgEmbed#10]
Hello,

i have some svg with hyperlinks inside. Dokuwiki himself show's /rendered the svg as image. 
So links not work.

When I activate this plugin the whole page is empty. Nothing will be displayed. When i inspect den HTML CODE with F12 the 
section "div class="dw-content" doesnt appear. 

After disable the plugin everthing will be display, but the svg as image.

Is this a bug or do I make a mistake.

Thanks
Christian

**Comment by restlessminded** [comment]
What template are you using?

**Comment by restlessminded** [comment]
My test SVG file has hyperlinks, so that's not at issue.  It sounds like it's not working with your template, maybe.

Also, what operating system, server and PHP version are you using?  Fastcgi or module?

**Comment by FiC5020** [comment]
I use the Template bootstrap3 but the orginal dokuwiki also dont work.

Operation System: debian 10 with Apache2 and PHP 7.3
Linux srvdoku 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
VM on VMware 6

I attached a Printout of the phpinfo().

[phpinfo.pdf](https://github.com/restlessminded/dokuwiki-plugin-svgEmbed/files/6622473/phpinfo.pdf)

**Comment by restlessminded** [comment]
I'm running Apache 2.4.29/PHP 7.2.24 under Ubuntu 18.04.05 LTS, but I don't _think_ that would be the problem (also, that's the most current in mainline for 18.04, so that's where I'm at).  Also, the only Apache modules I'm running that you're not are mod_rewrite, mod_socache_shmcb and mod_ssl, none of which should affect anything to do with this.

I don't see any XML sections in your phpinfo.  [Do you have libxml installed?](https://www.php.net/manual/en/book.libxml.php)  The code actually reads the XML to attempt to get dimensions so it requires it.  It may be borking on the `simplexml_load_file()` call.

**Comment by restlessminded** [comment]
Oh, as a note:  I flipped my test wiki back over to the default template and everything still worked as expected, so it's not the template per se.  I suspect it's that you need to install XML support for PHP.

**Comment by FiC5020** [comment]
now it works.

apt-get install -y php-simplexml

thanks
