### ISSUE TITLE
Section edit flickers

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [restlessminded/dokuwiki-plugin-svgEmbed#2]
Hi,

the section edit function gets a bit confused when this section contains an SVG image.

Best regards
Juergen

**Comment by restlessminded** [comment]
Yes, I see that it "flickers" in some cases.  In a couple cases, too, it doesn't do it in Chrome but it will in Firefox for the same page.

Let me look into that.  I've seen similar behavior before from other plugins and certain stylesheet markups but never bothered to try to fix them because I had more pressing issues to handle so I am flying a bit blind on this one.

**Comment by restlessminded** [comment]
Okay, I found the issue.

The upshot is, when you hover the button it calls out to the server to get HTML set up for section highlighting.  This works as expected, but since the embed isn't rendered yet the section collapses to the smaller size.  So then, you're not doing a mouseover on the button, so it goes back to the original size, and then you're hovering, so it goes to the smaller size, etc.  Thus, flicker.

I am going to wrap it in a div set with the size needed.  That way, it doesn't collapse and everything works as expected from a user standpoint.

I'll try to make the changes over the next day or two.

**Comment by restlessminded** [comment]
I believe I just fixed this one.  Please update and verify.  I'm still curious what browser you were using.

I still need to update the documentation; I made quite a few changes in this one (basically, in fixing it also allowed me to make some things "features" in a way).  It should still work by default, though.

**Comment by restlessminded** [comment]
[Finished documentation earlier this evening.](https://www.dokuwiki.org/plugin:svgembed)

**Comment by Juergen-aus-Koeln** [comment]
Excellent, now everything works perfectly

(Your question: I'm using Firefox)

**Comment by restlessminded** [comment]
Excellent!  Thanks for the follow-up!

For the record, I actually wrapped it in a span instead, but either way I'm glad it's fixed.
