### ISSUE TITLE
Media manager indicates no use

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [restlessminded/dokuwiki-plugin-svgEmbed#3]
Hi,

the media manager indicates that the SVG file is not in use. Therefore, there is a certain danger that it will be accidentally deleted:
![Mediamaneger](https://user-images.githubusercontent.com/1800472/69630031-e98b4980-104c-11ea-863c-bffb747184a9.png)

Best regards
Juergen

**Comment by restlessminded** [comment]
You noticed that too?  😁  I saw it but sighed heavily and left it be because I wanted to make sure the existing commit fixed the existing issues you reported.

Fortunately it's a holiday week here in the States, so nobody's expecting me to get anything accomplished to speak of at work.  I'll study what the problem is and fix it today.

**Comment by restlessminded** [comment]
Actually, on my test wiki I removed my plugin and it still doesn't show it.  This is probably the normal behavior, because in the instructions at the Dokuwiki.org site I explain how to hack the media manager to allow the upload of SVG.  However, other functions don't seem to support it because it's not recognizing it as an image.

I'll look to see if I can find a workaround to make it show it.

**Comment by restlessminded** [comment]
Actually, that's not it... once I edited the page it shows up.  Hmmm.

**Comment by restlessminded** [comment]
Okay, this one's in the bag.  It should work if you update (again!).  That one was a trip.

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much !!!
After editing the page including the SVG diagram the media manager shows the usages.

Best regards
Juergen

**Comment by Juergen-aus-Koeln** [comment]
Please update the file "plugin.info.txt", otherwise the extension manager will still indicate that you should update the plugin.

**Comment by restlessminded** [comment]
Yes, sorry; I thought I had, but it was the day before.  It's what I get when I am trying to do it interleaved with other things at work!
