### ISSUE TITLE
SVG is microscopic!

### ISSUE THREAD

**Issue by lizat** [restlessminded/dokuwiki-plugin-svgEmbed#5]
My link looks like this:
`{{:process_images:overviews:1000_tuvens.svg|Tuvens Overview}}`

I have tried with a width as well, my config is left as default. And I have updated mime.local.conf. The svg is valid and displays in the browser from the local file: https://www.screencast.com/t/E0vkRSXg88P5

I am using Bootstrap3 template. I do have the image mapping plugin active.

What should I do?

**Comment by restlessminded** [comment]
Can you supply an .svg file that is exhibiting the issue in your setup?  I'll see if I can recreate the issue on my side when I get an opportunity.

**Comment by lizat** [comment]
Try this... it is produced by Visio:



[1000_Tuvens.zip](https://github.com/restlessminded/dokuwiki-plugin-svgEmbed/files/4614756/1000_Tuvens.zip)

**Comment by restlessminded** [comment]
Definitely confirmed; I see what you mean when I load added the file to my media and then linked it in a test page.

It happens in the Monobook template (what I use).  I also have image mapping installed as it so happens, so let me see what I can figure out.

**Comment by restlessminded** [comment]
The good news is:  I see the problem!  The width attribute is in inches rather than pixels, so it's definitely a problem in my code; for that particular file it produces a 17x12 embed because the file is 16.5354 in x 11.6929 in; when I process the data it gets rounded off to the 17x12.

I need to consider how I want to approach this.  Do I want to do a certain DPI?  What about printing versus viewing (although to be fair, I only handle the xhtml renderer, so that may not be an issue)?  Do I want to use the viewbox values instead?

**Comment by restlessminded** [comment]
Actually, [the CSS3 specification](https://www.w3.org/TR/css-values-3/#compat) specifies that styling should assume 96 DPI.  I will implement around that, it seems reasonable.  Also, I will likely only support [absolute length units](https://www.w3.org/TR/css-values-3/#absolute-lengths) and not [relative length units](https://www.w3.org/TR/css-values-3/#relative-lengths), but that won't affect your use case.

I'll try to work on it in the next couple days.

**Comment by restlessminded** [comment]
The issue is resolved and I have placed a new version of the software in the repository.  You should be able to update your wiki from the Extension Manager and try out the changes.  Please let me know if it resolves your issue!

**Comment by restlessminded** [comment]
Did you get an opportunity to see if this resolved the issue for you, @lizat?
