### ISSUE TITLE
Making it responsive

### ISSUE THREAD

**Issue by lizat** [restlessminded/dokuwiki-plugin-svgEmbed#6]
Hello Michael,

The plugin is now behaving well. I have one questions (sorry it's in Issues) and that is can I make the image responsive. i have tried to do this using CSS but since one must either specify a width or it defaults I am wondering if this is not possible?

Thank you,

Liz

**Comment by restlessminded** [comment]
Let me take a look when I get some free time.

I will readily admit I write mostly native desktop and server-side code, so I'm not 100% on what people mean by "responsive" apart from something to do with mobile (I know the term, but I don't actually deal with that so much).  I guess it's time to learn... :grin:

**Comment by restlessminded** [comment]
Here's a quick rundown on what I did this evening:  I looked up the specs, and for `embed` and `object` tags you have to use CSS pixels for height and width.  In response to that, I changed the output to do the height and width in styles instead, and with that I can output other units, percentages or vw units.

After that, I did some initial code on my test wiki that adds a new parameter to the link that tells it to do responsive output instead.  Since I've done that, I've had second thoughts where maybe I could make the parameter be something like `units:<unit>` and you can specify what units you want to use.  If you do a link like

  `{{myfile.svg?30|This is my file}}`

Then your image will be done as normal in CSS pixels, but if you add an added parameter as so:

  `{{myfile.svg?30&units:vw}}`

the output would be modified to use the `style` parameter of the tag and be output in viewport units, or

  `{{myfile.svg?30%units:%}}`

would do the same, but do it in percentages.

I'm going to turn in and reflect on this a bit more tomorrow to weigh implementation issues.

**Comment by lizat** [comment]
Thank you Micheal, that sounds promising and would mean I could use % which should mean it will resize with the window.

**Comment by restlessminded** [comment]
You're welcome!  I hope it's useful to you!

I am considering an additional change that lets you apply a class as well, so for additional items you can apply a CSS class.  I might look at doing the same, but an ID as well, for similar reasons.

**Comment by restlessminded** [comment]
I'm finished.  I'll wrap it up and upload it tomorrow and update the documentation at the main Dokuwiki site.

Note I am still on Greebo because a lot of the third-party plugins I use needed editing to work when I tried to upgrade to Hogfather RC1, so I haven't tested against Hogfather yet.

**Comment by restlessminded** [comment]
I'm uploading the changes; it should be ready in about an hour.  Let me know how it works for you!
