### ISSUE TITLE
Opening xlinks - notes

### ISSUE THREAD

**Issue by lizat** [restlessminded/dokuwiki-plugin-svgEmbed#7]
Hi Michael,

I think this isn't a bug as such but you should know about it. I was going to add something to the plugin page but thought you would rather do it.

I use the latest version of Bootstrap3 template and I have a side bar which uses Indexmenu.
I am producing my SVG files from Visio diagrams, they have hotspots. I then edit the SVG file to change the xlink to link to the relevant page in the wiki. What is very pleasing is that now it is responsive the hotspots are also so I don't have to do anything additional. the links work but what they do is load the page in the body of the existing page, by which i mean i get the new page loaded in the body of the original page, including the sidebar - so i have the side bar, the body and the body contains the sidebar and body of the new page like this: https://www.screencast.com/t/cYZ0t7Ynt. 

I have played about and the workaround is that I now add a show parameter like this:
```
<a xlink:href="http://wiki.tuvens.com/doku.php?id=process:1100_manage_events:1100_manage_events "
				xlink:title="[1100] Manage Events, overview"
				xlink:show="new">
```
This works although may be annoying for some people as you could end up with multiple tabs and no paging backwards through your journey.

The other thing is that although W3Schools doesn't say this according to Mozilla the show parameter is going to be deprecated.

So I don't know why the link doesn't reload the whole page (could it be a Bootstrap issue?) or where there is another way I can force this to load but at least there is a workaround.

Thank you for the plug-in!

Liz

**Comment by restlessminded** [comment]
Did you see issue #4?  This might be related and has some suggestions to go about setting targets directly in the .SVG source.

**Comment by restlessminded** [comment]
Okay, I follow what you're saying.  It's that it's targeting the wrong frame, but if you link it with the provided "hint" then it loads correctly.

Yeah, targeting of embedded links was largely what #4 was about.  The problem is that SVG is its own document, so we have to play within the conventions, but since to make hotspots work it has to be embedded it limits some of the options.  The options are (ever so slightly) better when we write the HTML by hand, but we're using a CMS so here we are.

I [see what you were referring to on MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:show) the notice of the `xlink:show` attribute being deprecated, but it does specify that [you could use target in its place](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/target); perhaps you could set it up as so:

    <a xlink:href="http://wiki.tuvens.com/doku.php?id=process:1100_manage_events:1100_manage_events "
                                    xlink:title="[1100] Manage Events, overview"
                                    target="_blank">

to achieve the same effect, or:

    <a xlink:href="http://wiki.tuvens.com/doku.php?id=process:1100_manage_events:1100_manage_events "
                                    xlink:title="[1100] Manage Events, overview"
                                    target="_top">

to potentially open it in the same page?

\
P.S.  W3Schools is... well, W3Schools.  :grinning:  I tend to favor MDN.  I sure do miss Webmonkey sometimes, though...

**Comment by lizat** [comment]
Hi Michael,

I must have been asleep because I tried adding target and it failed BUT I retried now and it is fine, I think I was tired before and probably didn't notice a typo. 

So that is great.... I will add a note to the plug in page to help others - and which you can adjust as you see fit

W3S - yes but it's got a lot of people going which is good
WDN - fab
Webmonkey - shame!

Thank you.............................. liz

**Comment by restlessminded** [comment]
Glad it's working for you now!  Once you are done with the edits I will collect information from #4 and make a new section on that page with hints about setting up your SVG files for different cases.
